---
- hosts: server
  sudo: True
  tasks:
  - name: Import the public key used by the package management system
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927 state=present
  - name: Add MongoDB repository
    lineinfile: "dest=/etc/apt/sources.list.d/mongodb-org-3.2.list create=yes line='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse'"
  - name: install mongodb
    apt: pkg=mongodb-org state=latest update_cache=yes
    notify:
    - start mongodb
  handlers:
    - name: start mongodb
      service: name=mongod state=started
