---
- hosts: server
  sudo: yes

  tasks:
    - name: get software for apt repositoty management
      apt: name={{ item }} state=installed
      with_items:
        - python-apt
    - name: Import the public key used by the package management system
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927 state=present
    - name: Add MongoDB repository
      shell: >
        echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
    - name: install mongodb
      apt: pkg=mongodb-org state=latest update_cache=yes
      notify:
        - start mongodb
  handlers:
    - name: start mongodb
      service: name=mongod state=started
